### ISSUE TITLE
Legitimacy bar partners

### ISSUE THREAD

**Issue by jsduffy** [startsole/startsole.org#32]
This could include School in the Cloud, TIES, Barbara Jacobs, Share your Learning, XQ (check on that), SOLE Colombia (check on that)

**Comment by jsduffy** [comment]
School in the Cloud
  TIES
  Barbara Jacobs
  Share your Learning
  XQ (check on that)
  SOLE Colombia

**Comment by jsduffy** [comment]
NSF
  Wonderopolis
  STEM Ecosystems
  Right Question Institute

**Comment by jsduffy** [comment]
How many do we want total? Let's choose a number and then choose the best options to fill that many slots. 6? 9? Probably 6

**Comment by drewrwilson** [comment]
Email Jeff asking for a list of 6

**Comment by jsduffy** [comment]
From Jeff:
XQ,PAST, All the ESCs we collaborate with.  Jennings Foundation, The Right Question Institute (if its ok),  Share your learning, Wonderopolis (if its ok), DBJ Foundation, Andy Chailef, CSU STEMM Center, CSU UTEACH, Envision Excellence for STEM Education, Microsoft Giving Network (I need to get the right name for this), HRSA, HPAC,  Indigo Strategies
